version: '3.7'
services:
  frontend:
    build:
      context: ./frontend_new
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend_new:/usr/src/app
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./backend:/var/www
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:80"  # Expose port 8000 on localhost to map to port 80 in the container
    volumes:
      - ./backend:/var/www  # Mount the backend code inside NGINX
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # NGINX configuration
    depends_on:
      - backend
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
